#!/usr/bin/env python3
"""Unattended slice loop. Haiku 4.5 executes; this driver judges, commits, pushes.

Usage:  .venv/Scripts/python ops/haiku-runner/driver.py            (run / resume)
        .venv/Scripts/python ops/haiku-runner/driver.py --dry-run  (print the plan)
        .venv/Scripts/python ops/haiku-runner/driver.py --only P01a
Restart is always safe: state lives in ops/haiku-runner/state.json.
"""
import argparse, datetime, fnmatch, json, os, re, shutil, subprocess, sys, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS = ROOT / "ops" / "haiku-runner"
STATE = OPS / "state.json"
LOG = OPS / "driver.log"
LOCK = OPS / ".lock"
BLOCKERS = OPS / "blockers"
STATUS = OPS / "STATUS.md"
PLANS = ROOT / "Plans.md"
PY = str(ROOT / ".venv" / "Scripts" / "python.exe")
HAIKU = "claude-haiku-4-5-20251001"
TRAILER = "Co-Authored-By: Claude Haiku 4.5 <noreply@anthropic.com>"
MAX_ATTEMPTS = 3
BASELINE_RED_JOBS = ("Dependency audits",)  # red at donor seed commit (npm advisories); owner decision, not runner scope
LIMIT_SLEEP_S = 20 * 60
LIMIT_RE = re.compile(
    r"(usage limit|rate.?limit|limit reached|hit your limit|limit will reset|resets? (at|in)|"
    r"overloaded|\b529\b|too many requests|quota|out of (extra )?usage)", re.I)
DISALLOWED = ["Bash(git commit:*)", "Bash(git push:*)", "Bash(git reset:*)", "Bash(git clean:*)",
              "Bash(git checkout:*)", "Bash(git stash:*)", "Bash(git add:*)", "Bash(git remote:*)", "Bash(git config:*)",
              "Bash(curl:*)", "Bash(gh:*)", "Bash(wget:*)", "Bash(ssh:*)", "Bash(scp:*)", "Bash(nc:*)",
              "Bash(powershell:*)", "Bash(pwsh:*)", "Bash(cmd:*)", "Bash(reg:*)", "Bash(taskkill:*)", "Bash(net:*)",
              "Bash(rm -r:*)", "Bash(rm -fr:*)", "Bash(rmdir:*)", "Bash(rd:*)", "Bash(del:*)",
              "Bash(*_radar_private*)"] + [f"{t}({pat})" for t in ("Read", "Edit", "Write") for pat in (
                  "../_radar_private/**", "../../_radar_private/**", "**/_radar_private/**",
                  "//c/Users/Zarinpal/Documents/Personal Formal Documents/Apply/_radar_private/**")]

sys.path.insert(0, str(OPS))
import manifest  # noqa: E402


def log(msg):
    line = f"{datetime.datetime.now():%Y-%m-%d %H:%M:%S} {msg}"
    print(line, flush=True)
    with open(LOG, "a", encoding="utf-8") as f:
        f.write(line + "\n")


def sh(cmd, cwd=ROOT, timeout=1800, input_text=None, env=None):
    p = subprocess.run(cmd, cwd=cwd, shell=isinstance(cmd, str), capture_output=True, text=True,
                       encoding="utf-8", errors="replace", timeout=timeout, input=input_text, env=env)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def git(*a):
    return sh(["git", *a])


def load_state():
    if STATE.exists():
        return json.loads(STATE.read_text(encoding="utf-8"))
    return {"slices": {}, "ci_red": [], "started": str(datetime.datetime.now())}


def save_state(st):
    STATE.write_text(json.dumps(st, indent=2), encoding="utf-8")


def sstate(st, sid):
    return st["slices"].setdefault(sid, {"status": "pending", "attempts": 0})


def write_plans(st):
    lines = ["# Plans.md — Academic Radar (generated by ops/haiku-runner/driver.py)", "",
             "Source of truth: docs/authority/03_EXECUTION/CLAUDE_CODE_EXECUTION_INTAKE.md (P00–P22).", ""]
    for s in manifest.SLICES:
        s_ = st["slices"].get(s["id"], {"status": "pending"})
        mark = {"done": "x", "blocked": "!", "deferred": "~"}.get(s_["status"], " ")
        lines.append(f"- [{mark}] `{s['id']}` {s['title']} ({s_['status']})")
    PLANS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    counts = {}
    for s in manifest.SLICES:
        k = st["slices"].get(s["id"], {"status": "pending"})["status"]
        counts[k] = counts.get(k, 0) + 1
    out = [f"# Runner status ({datetime.datetime.now():%Y-%m-%d %H:%M})", "", f"Counts: {counts}", ""]
    for s in manifest.SLICES:
        s_ = st["slices"].get(s["id"], {})
        if s_.get("status") == "blocked":
            out += [f"## BLOCKED {s['id']} — {s['title']}", s_.get("blocker", "(no text)"), ""]
        if s_.get("status") == "deferred":
            out += [f"## DEFERRED (needs stronger model) {s['id']} — {s['title']}", s.get("defer_note", ""), ""]
    if st.get("ci_red"):
        out += ["## CI red at", ", ".join(st["ci_red"]), ""]
    STATUS.write_text("\n".join(out), encoding="utf-8")


def render_prompt(s, feedback):
    pre = (OPS / "PREAMBLE.md").read_text(encoding="utf-8")
    body = [f"SLICE_ID: {s['id']}", f"TITLE: {s['title']}", "", "READ (only these):"]
    body += [f"- {r}" for r in s.get("read", [])] or ["- (nothing)"]
    body += ["", "STEPS:"] + [f"{i}. {t}" for i, t in enumerate(s["steps"], 1)]
    body += ["", "ALLOWED PATHS (glob):"] + [f"- {p}" for p in s["allowed"]]
    body += ["", "GATE (the driver runs these after you finish; all must exit 0):"]
    body += [f"- {g}" for g in manifest.expand_gates(s, PY)]
    if feedback:
        body += ["", "PREVIOUS ATTEMPT FAILED. Fix exactly this, change nothing else:", feedback]
    return pre + "\n\n" + "\n".join(body) + "\n"


def run_haiku(prompt, max_turns):
    claude = shutil.which("claude") or "claude"
    env = dict(os.environ, MAX_THINKING_TOKENS="0", PYTHONIOENCODING="utf-8")
    cmd = [claude, "-p", "--model", HAIKU, "--output-format", "json", "--max-turns", str(max_turns),
           "--no-session-persistence", "--tools", "Bash,Read,Edit,Write,Grep,Glob",
           "--strict-mcp-config", "--mcp-config", '{"mcpServers":{}}', "--setting-sources", "local",
           "--disable-slash-commands", "--allowedTools", "Bash,Read,Edit,Write,Grep,Glob",
           "--disallowedTools", ",".join(DISALLOWED)]
    try:
        rc, out = sh(cmd, timeout=2400, input_text=prompt, env=env)
    except subprocess.TimeoutExpired:
        return "error", "timeout after 40 min"
    text, is_err = out, rc != 0
    try:
        d = json.loads(out.strip().splitlines()[-1]) if out.strip() else {}
        text = str(d.get("result", "")) or out
        is_err = bool(d.get("is_error")) or rc != 0
        if str(d.get("subtype", "")).startswith("error_max_turns"):
            return "error", "max turns exhausted"
    except Exception:
        pass
    if (is_err or not text.strip()) and LIMIT_RE.search(out):
        return "limit", out[-400:]
    if is_err:
        return "error", out[-600:]
    return "ok", text


def status_paths():
    _, out = git("status", "--porcelain", "-uall")
    paths = []
    for ln in out.splitlines():
        if not ln.strip():
            continue
        p = ln[3:].strip().strip('"')
        if " -> " in p:
            p = p.split(" -> ")[-1]
        paths.append((ln[:2], p.replace("\\", "/")))
    return paths


def enforce_paths(s, pre=frozenset()):
    allowed = list(s["allowed"]) + ["astra/tests/academic_radar/**", "ops/haiku-runner/blockers/*",
                                    "ops/haiku-runner/state.json", "Plans.md", "ops/haiku-runner/STATUS.md"]
    bad = []
    for code, p in status_paths():
        if p in pre:
            continue
        if not any(fnmatch.fnmatch(p, g) for g in allowed):
            bad.append(p)
            if code.strip() == "??":
                try:
                    (ROOT / p).unlink()
                except OSError:
                    pass
            else:
                git("checkout", "--", p)
    return bad


def run_gates(s):
    for g in manifest.expand_gates(s, PY):
        rc, out = sh(g, timeout=1800)
        if rc != 0:
            return False, f"GATE FAILED: {g}\n" + "\n".join(out.strip().splitlines()[-60:])
    return True, ""


def stash_failed(s):
    git("stash", "push", "-u", "-m", f"failed-{s['id']}-{int(time.time())}")


def commit_push(s, st):
    git("add", "-A")
    rc, out = git("commit", "-m", f"feat({s.get('phase', 'radar')}): {s['id']} {s['title']}\n\n{TRAILER}")
    if rc != 0 and "nothing to commit" not in out:
        return False, out
    rc, out = git("push", "origin", "main")
    if rc != 0:
        rc, out2 = git("pull", "--rebase", "origin", "main")
        rc, out = git("push", "origin", "main")
    return rc == 0, out


def ci_status(sha):
    """Non-blocking. Returns ('pending'|'ok'|'red', log_text)."""
    rc, out = sh(["gh", "run", "list", "--branch", "main", "--commit", sha, "--json",
                  "databaseId,status,conclusion,name", "--limit", "10"])
    try:
        runs = json.loads(out) if rc == 0 else []
    except Exception:
        runs = []
    if not runs or any(r["status"] != "completed" for r in runs):
        return "pending", ""
    bad = [r for r in runs if r["conclusion"] not in ("success", "skipped", "neutral")]
    if not bad:
        return "ok", ""
    failing, seen = [], False
    for r in bad:
        _, jo = sh(["gh", "run", "view", str(r["databaseId"]), "--json", "jobs"])
        try:
            jobs = json.loads(jo)["jobs"]
            seen = True
        except Exception:
            jobs = []
        failing += [j["name"] for j in jobs if j["conclusion"] not in ("success", "skipped", "neutral")]
    failing = [n for n in failing if n not in BASELINE_RED_JOBS]
    if seen and not failing:
        return "ok", ""
    _, logs = sh(["gh", "run", "view", str(bad[0]["databaseId"]), "--log-failed"])
    keep = [l for l in logs.splitlines() if not any(b in l for b in BASELINE_RED_JOBS)]
    return "red", "\n".join(keep[-150:])


def resolve_ci(st, block):
    """Check the pending CI run. block=False returns immediately if it is still running."""
    limit = time.time() + 45 * 60
    while st.get("ci_pending"):
        pend = st["ci_pending"]
        state, logs = ci_status(pend["sha"])
        if state == "pending":
            if not block:
                return
            if time.time() >= limit:
                log(f"CI still pending for {pend['sha'][:8]} after 45 min; not waiting any longer")
                st["ci_red"].append(pend["sha"][:8] + "?")
                st["ci_pending"] = None
                return
            time.sleep(60)
            continue
        if state == "ok":
            log(f"CI green (baseline-red jobs ignored) at {pend['sha'][:8]}")
            st["ci_pending"] = None
            return
        if pend["tries"] >= 2:
            log(f"CI red at {pend['sha'][:8]}; giving up after 2 fix attempts")
            st["ci_red"].append(pend["sha"][:8])
            st["ci_pending"] = None
            return
        pend["tries"] += 1
        log(f"CI red at {pend['sha'][:8]}; fix attempt {pend['tries']}")
        fx = {"id": f"{pend['slice']}-ci{pend['tries']}", "title": "fix CI failure", "phase": "ci",
              "read": [], "steps": ["Read the CI failure log below. Make the minimal change so CI passes on Linux. "
                                    "Change nothing unrelated.\n" + logs[-3500:]],
              "allowed": ["astra/**", "dashboard/**", ".github/workflows/ci.yml", "docker-compose*.yml", "scripts/**"],
              "gates": [manifest.be_fast()], "max_turns": 40}
        if do_slice(fx, st):
            _, sha2 = git("rev-parse", "HEAD")
            pend["sha"] = sha2.strip()
        else:
            st["ci_red"].append(pend["sha"][:8])
            st["ci_pending"] = None
        save_state(st)


def do_slice(s, st):
    ss = sstate(st, s["id"])
    feedback = ss.get("feedback", "")
    st["in_progress"] = s["id"]
    save_state(st)
    attempts = 0
    while attempts < MAX_ATTEMPTS:
        attempts += 1
        ss["attempts"] += 1
        log(f"{s['id']} attempt {attempts}/{MAX_ATTEMPTS}")
        pre = frozenset(p for _, p in status_paths())
        for stale in list(ROOT.glob(f"**/blockers/{s['id']}.md")):  # stale blocker files must not trigger BLOCKED
            if ".venv" not in stale.parts and "node_modules" not in stale.parts:
                stale.unlink()
        while True:
            kind, text = run_haiku(render_prompt(s, feedback), s.get("max_turns", 110))
            if kind == "limit":
                log(f"usage/rate limit hit; sleeping {LIMIT_SLEEP_S // 60} min. {text[:120]!r}")
                time.sleep(LIMIT_SLEEP_S)
                continue
            break
        bf = BLOCKERS / f"{s['id']}.md"
        stray = [p for p in ROOT.glob(f"**/blockers/{s['id']}.md")
                 if ".venv" not in p.parts and "node_modules" not in p.parts]
        if stray and not bf.exists():
            bf.parent.mkdir(parents=True, exist_ok=True)
            bf.write_text(stray[0].read_text(encoding="utf-8"), encoding="utf-8")
            for p in stray:
                if p != bf:
                    p.unlink()
        if bf.exists() or re.search(r"^\s*BLOCKED\s*$", text, re.M):
            btxt = bf.read_text(encoding="utf-8") if bf.exists() else text[-800:]
            stash_failed(s)
            BLOCKERS.mkdir(parents=True, exist_ok=True)
            bf.write_text(btxt, encoding="utf-8")
            ss.update(status="blocked", blocker=btxt[:1500])
            st["in_progress"] = None
            log(f"{s['id']} BLOCKED by executor")
            return False
        if kind == "error":
            feedback = f"Executor error: {text}"
            log(f"{s['id']} executor error: {text[:200]}")
            continue
        bad = enforce_paths(s, pre)
        ok, fb = run_gates(s)
        if bad:
            fb = f"You wrote outside ALLOWED PATHS (driver reverted): {bad}\n" + fb
        if ok and not bad:
            break
        feedback = fb
        log(f"{s['id']} gate fail: {fb[:300]}")
    else:
        stash_failed(s)
        ss.update(status="blocked", blocker=f"Gate failed {MAX_ATTEMPTS}x. Last output:\n{feedback[:1400]}")
        st["in_progress"] = None
        log(f"{s['id']} BLOCKED after {MAX_ATTEMPTS} attempts")
        return False
    ss.update(status="done", feedback="")
    save_state(st)
    write_plans(st)
    ok, out = commit_push(s, st)
    _, sha = git("rev-parse", "HEAD")
    ss["sha"] = sha.strip()
    log(f"{s['id']} DONE {sha.strip()[:8]} push={'ok' if ok else 'FAILED ' + out[-120:]}")
    st["in_progress"] = None
    if s.get("ci") and ok:
        resolve_ci(st, block=True)  # settle any earlier pending run first
        st["ci_pending"] = {"sha": sha.strip(), "slice": s["id"], "tries": 0}
    save_state(st)
    write_plans(st)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only")
    a = ap.parse_args()
    st = load_state()
    if a.dry_run:
        for s in manifest.SLICES:
            print(s["id"], "deps=", s.get("deps", []), "|", s["title"])
        return
    if LOCK.exists():
        try:
            pid = int(LOCK.read_text())
            rc, out = sh(f'tasklist /FI "PID eq {pid}"')
            if str(pid) in out:
                print("driver already running, pid", pid)
                return
        except Exception:
            pass
    LOCK.write_text(str(os.getpid()))
    git("config", "core.longpaths", "true")
    for s in manifest.SLICES:
        if s.get("defer"):
            sstate(st, s["id"])["status"] = "deferred"
    while True:
        progressed = False
        resolve_ci(st, block=False)
        for s in manifest.SLICES:
            if a.only and s["id"] != a.only:
                continue
            ss = sstate(st, s["id"])
            if ss["status"] != "pending":
                continue
            if any(st["slices"].get(d, {}).get("status") != "done" for d in s.get("deps", [])):
                continue
            own = {"ops/haiku-runner/state.json", "ops/haiku-runner/STATUS.md", "Plans.md"}
            dirty = [p for _, p in status_paths() if p not in own]
            if dirty and st.get("in_progress") not in (None, s["id"]):
                log(f"orphan work from {st['in_progress']} found before {s['id']}; stashing it")
                git("stash", "push", "-u", "-m", f"orphan-{st['in_progress']}-{int(time.time())}")
                save_state(st)
                write_plans(st)
            elif dirty:
                log("resuming same slice on top of its partial work")
            ok = do_slice(s, st)
            save_state(st)
            write_plans(st)
            progressed = True
            break
        if not progressed:
            break
        if a.only:
            break
    resolve_ci(st, block=True)
    save_state(st)
    pend = [s["id"] for s in manifest.SLICES if sstate(st, s["id"])["status"] == "pending"]
    log("HALT: nothing runnable. pending-but-blocked-by-deps: %s" % pend if pend else "COMPLETE: all runnable slices done")
    write_plans(st)
    git("add", "-A")
    git("commit", "-m", f"chore: runner status\n\n{TRAILER}")
    git("push", "origin", "main")
    LOCK.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
